### PR TITLE
Adding a revive system to MalumMenu

### PR DESCRIPTION
**Pull request by lekillerdesgames**
I found this menu one day ago and found it cool but it was missing something, the ability to revive.
So I decided to code it myself, I tested it and it works pretty well. Note that it's not an rpc means only the client sees players revive, sadly I can't do anything about that but it might be useful because now, if the client wants to revive after being ejected / killed, he can go ahead and even kill again if he's impostor.
Thing I added:
- a new SubMenu named "Revive"
- the ability to revive the selected player (using the shapeshift menu)
- the ability to revive every dead players
Here are some screenshots:

Menu with revive features added:
revive menu

Menu shown when using the revive player ability:
revive player

Players after using the revive all ability:
revive all

Feel free to add my code to the original mod and hope I helped!
My discord: lekillerdesgames

### CODE REVIEW

**Review by astra1dev — APPROVED** [review]
great idea, good code 🤗

**Comment by lekillerdesgames** [comment]
> great idea, good code 🤗

ty (:

**Comment by scp222thj** [comment]
@lekillerdesgames ...your README edits are part of the PR lol

**Comment by lekillerdesgames** [comment]
> @lekillerdesgames ...your README edits are part of the PR lol

ik I gotta close this pr lol

**Pull request closed without merging**
