### PR TITLE
Improved README (once again lol)

### PR DESCRIPTION
**Pull request by astra1dev**
- added "building" with instructions if someone wants to build MM for e.g. older AU versions
- Added Links to AUWiki and BepInEx in "contributing" tab
- Improved "Releases" and "Installation" (explanation easier to understand now)

### CODE REVIEW

**Comment by scp222thj** [comment]
I think for now we can stick with the current README, I prefer it a bit. I think the Building section is more or less covered by the Reactor documentation we provide, and the note you added in Installation isn't really required because people can still follow the normal installation without issue if they already have BepInEx installed.

However, I like your idea of adding more resources to the contribution section. I think I'm gonna add the [among-us-protocol](https://github.com/roobscoob/among-us-protocol) guide because it is similar but a bit more informative than the [AUWiki](https://auwiki.duikbo.at/)

**Comment by astra1dev** [comment]
no problem :)

**Comment by astra1dev** [comment]
but uhh among us protocol repo is outdated, so idk

**Comment by scp222thj** [comment]
Isn't [AUWiki](https://auwiki.duikbo.at/) outdated too? I just chose the [among-us-protocol(https://github.com/roobscoob/among-us-protocol) guide because it has a bit more content. 

(Btw thx for the quick response lmao)

**Comment by scp222thj** [comment]
I'm just going to add both to the README, since they both stopped being maintained more or less at the same time

**Pull request closed without merging**
