### PR TITLE
Add [Revive Player] Only Host Cheat

### PR DESCRIPTION
**Pull request by Night-GUA**

### CODE REVIEW

**Comment by astra1dev** [comment]
W

**Comment by Night-GUA** [comment]
And Change Imp number
And Send AUMRpc By Everyone

**Comment by scp222thj** [comment]
I already have an implementation in mind for the revive cheat so I think I'll code my own. However, send AUM rpc by everyone is actually quite an interesting concept, never really thought about that lol. I'll take a look at the code 👍

**Comment by Night-GUA** [comment]
You showlld use `Send AUM Rpc by everyone` cheat on +25 mode

**Comment by NikoCat233** [comment]
Not working since innersloth is putting networked playerinfo server side

**Comment by scp222thj** [comment]
Revive or the AUM cheat?

**Comment by Night-GUA** [comment]
revive

**Comment by ReactorCoreDev** [comment]
PlayerControl.LocalPlayer.Revive(); is not host only

**Pull request closed without merging**
