### PR TITLE
bypass chat limit

### PR DESCRIPTION
**Pull request by hs233666**

### CODE REVIEW

**Review by astra1dev — APPROVED** [review]
I tested the code, it's working fine. 
Only question I have is what the replaceDic is for since it's not used by anything as far as i can tell...

**Comment by hs233666** [comment]
> I tested the code, it's working fine. Only question I have is what the replaceDic is for since it's not used by anything as far as i can tell...

The dictionary is used to replace special characters to normal characters
IDK how to allow putting special characters

**Comment by astra1dev** [comment]
but its not used by anything, not even AU methods, and there is nothing similar...

**Comment by hs233666** [comment]
Seems like its finished

**Comment by scp222thj** [comment]
Yeah, thanks so much for the idea you gave us @hs233666, I was really able to develop it in interesting ways. Btw are you in our Discord server? Cause most of our development discussions happen there, so if you'd like to contribute I suggest you join too.

**Pull request closed without merging**
